const listaProdutos = [
  ["https://vicente321.github.io/imgs/moster_black.webp", "Monster Original", "Sabor original com muita força e energia", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/monster_branco.webp", "Monster Ultra", "Sabor cítrico. Sem acúcar!", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/monster_mango_logo.webp", "Monster Mango Loco", "Sabor suco de manga e mix de frutas críticas naturais", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/monster_watermelon.webp", "Monster Ultra Wattermellow", "Sabor melancia refrescante, zero açúcar.", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/monster_pipeline_punch.webp", "Monster Pipeline Punch", "O energético de sabor exótico, único, numa perfeita combinação dos sabores da goiaba, laranja e maracujá.", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/monster_pacific_punch.webp", "Monster Pacific Punch", "Sabor tropical que é leve, suave e o toque perfeito de doce", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster Energy Juice Khaos.jpeg", "Monster Energy Juice Khaos", "Suco de laranja com energético.", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster Energy Dragon Ice Tea Limão.jpeg", "Monster Energy Dragon Ice Tea Limão", "Sabor chá gelado de limão com energético", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster Energy Dragon Ice Tea Pêssego.jpeg", "Monster Energy Dragon Ice Tea Pêssego", "Sabor chá gelado de pêssego ", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster Energy Ultra Peachy Keen.jpeg", "Monster Energy Ultra Peachy Keen", "Sabor de pêssego e o nosso blend secreto de Monster Energy, zero açúcar. ", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster Ultra Fiesta.webp", "Monster Ultra Fiesta", "Sabor tropical de manga, zero açúcar.", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/Monster-Ultra-Paradise.png", "Monster Energy Ultra Paradise", "Sabor kiwi com maçã verde, zero açúcar. ", "ENERGÉTICO", "7.52"],
  ["https://vicente321.github.io/imgs/CCSA_LT_220ML.webp", "Coca Zero", "", "REFRIGERANTE", "2.40"],
  ["https://vicente321.github.io/imgs/110255_COCA---CCO220ml.webp", "Coca Lata", "", "REFRIGERANTE", "2.40"],
  ["https://vicente321.github.io/imgs/110255_COCA---CCO220ml.webp", "Fanta Lata", "", "REFRIGERANTE", "2.40"],
  ["https://vicente321.github.io/imgs/110255_COCA---CCO220ml.webp", "Agua com gas", "", "Agua", "1.65"],
];
