const listaProdutos = [
  ["https://vicente321.github.io/imgs/moster_black.webp", "Monster Original", "Sabor original com muita força e energia", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/monster_branco.webp", "Monster Ultra", "Com zero calorias e zero açúcar,", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/monster_mango_logo.webp", "Monster Mango Loco", "Com sabor doce e marcante e um toque especial de suco de manga", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/monster_watermelon.webp", "Monster Ultra Wattermellow", "Sabor intenso de melancia que proporciona uma sensação refrescante;", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/monster_pipeline_punch.webp", "Monster Pipeline Punch", "O energético de sabor exótico, único, numa perfeita combinação dos sabores da goiaba, laranja e maracujá.", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/monster_pacific_punch.webp", "Monster Pacific Punch", "Sabor tropical que é leve, suave e o toque perfeito de doce", "ENERGÉTICO", "7.40"],
  ["https://vicente321.github.io/imgs/paçoca.webp", "Paçoquinha", "", "DOCES", "1.00"],
  ["https://vicente321.github.io/imgs/kitkat_dark.webp", "KitKat Dark", "", "DOCES", "4.50"],
  ["https://vicente321.github.io/imgs/kitkat_tradicional.webp", "KitKat Tradicional", "", "DOCES", "4.50"],
  ["https://vicente321.github.io/imgs/jujuba_gomets.webp", "Jujuba Gumetes", "Sabores: iogurte e frutas ", "DOCES", "1.50"],
  ["https://vicente321.github.io/imgs/bis_extra_black.webp", "Bis Extra Black", "", "DOCES", "4.50"],
  ["https://vicente321.github.io/imgs/bis_extra.webp", "Bis Extra", "", "DOCES", "4.50"],
  ["https://vicente321.github.io/imgs/coca_mini.webp", "Mini Coca", "", "BEBIDA", "2.50"],
  ["https://vicente321.github.io/mini_fanta.webp", "Mini Fanta", "", "BEBIDA", "2.50"],
  ["https://vicente321.github.io/imgs/mini_guarana.webp", "Mini Guaraná", "", "BEBIDA", "2.50"],
  ["https://vicente321.github.io/imgs/agua_com_gas.webp", "Aguá com gás", "", "BEBIDA", "4.00"],
  ["https://vicente321.github.io/imgs/bombomLimao.webp", "Bom Bom Limão", "Com recheio cremoso de limão da fruta", "DOCES", "4.00"],
  ["https://vicente321.github.io/imgs/bombomMorango.webp", "Bom Bom Morango", "Com recheio cremoso de morango da fruta", "DOCES", "4.00"],
  ["https://vicente321.github.io/imgs/bombomMaracuja.webp", "Bom Bom de Maracujá", "Com recheio cremoso de maracujá da fruta", "DOCES", "4.00"],
  ["https://vicente321.github.io/imgs/paodemel.png", "Pão de Mel", "Com recheio cremoso de café", "DOCES", "5.00"],
  ["https://vicente321.github.io/imgs/mateleaoGas.webp", "Mate Leão com Gás", "", "BEBIDA", "5.50"],
  ["https://vicente321.github.io/imgs/CCSA_LT_220ML.webp", "Coca Zero", "", "BEBIDA", "4.50"],
  ["https://vicente321.github.io/imgs/fantaLaranjaLata.jpeg", "Fanta Laranja Lata", "", "BEBIDA", "4.00"],
  ["https://vicente321.github.io/imgs/ShewppesLata.jpeg", "Schweppes Lata", "", "BEBIDA", "4.00"],
  ["https://vicente321.github.io/imgs/guaranaMineiro.png", "Guaraná Mineiro", "", "BEBIDA", "2.50"],
  ["https://vicente321.github.io/imgs/fantaLaranjaLata.jpeg", "Powerade Laranja", "", "BEBIDA", "8.00"],
  ["https://vicente321.github.io/imgs/110255_COCA---CCO220ml.webp", "Coca Lata", "", "BEBIDA", "4.50"],
  ["https://vicente321.github.io/imgs/aguasemgas.webp", "Água sem gás", "", "BEBIDA", "3.00"],
  ["https://vicente321.github.io/imgs/geladinho.webp", "Geladinho Sabores", "", "DOCES", "1.50"],
  ["https://vicente321.github.io/imgs/tictac.jpeg", "TicTac Sabores", "Mix de sabores", "DOCES", "4.00"],
  ["https://vicente321.github.io/imgs/snickersOriginal.webp", "Snickers", "", "DOCES", "5.00"],
  ["https://vicente321.github.io/imgs/snickersDark.webp", "Snickers Dark", "", "DOCES", "5.00"],
  ["https://vicente321.github.io/imgs/snickersPeMoleque.webp", "Snickers Pé de Moleque", "", "DOCES", "5.00"],
  ["https://vicente321.github.io/imgs/balinhaAzeinha.jpg", "Azedinha", "Drops azedinho sabor Uva", "DOCES", "1.50"],
  ["https://vicente321.github.io/imgs/cafeCapsula.webp", "Café Cápsula", "", "CHÁ", "3.50"],
];
